name: hive_flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  double_back_to_close_app: ^2.1.0
  intl_phone_field: ^3.2.0
  flutter_spinkit: ^5.2.0
  pin_code_fields: ^8.0.1
  dio: ^5.3.4
  stop_watch_timer: ^3.0.2
  sms_autofill: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.2
  permission_handler: ^10.4.5
  get: ^4.6.5
  intl: ^0.17.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  http: ^1.0.0
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.10.0
  flutter_image_compress: ^2.0.4
  qr_code_scanner: ^1.0.1
  image_cropper: ^5.0.0
  flutter_speed_dial: ^7.0.0
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/h6.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
